import time
import os
i = os.system('cls')
time.sleep(0.5)
print("                #")
print("              # #")
print("            #   #")
print("          #     #########")
print("          # #   #    #     #")
print("          #   # # #           #")
print("################o###############")
print("  #           # # #   #")
print("     #     #    #   # #")
print("        #########     #")
print("                #   #")
print("                # #")
print("                #")
time.sleep(0.2)
i = os.system('cls')
print("")
print("      #")
print("      # #       #############")
print("      #   #   # #        #")
print("      #    ##   #     ##")
print("      #       # #  #     #")
print("      ##########o##########")
print("       #     #  # #       #")
print("         ##     #   ##    #")
print("       #        # #   #   #")
print("    #############       # #")
print("                          #")
time.sleep(0.2)
i = os.system('cls')
print("                #")
print("              # #")
print("            #   #")
print("          #     #########")
print("          # #   #    #     #")
print("          #   # # #           #")
print("################o###############")
print("  #           # # #   #")
print("     #     #    #   # #")
print("        #########     #")
print("                #   #")
print("                # #")
print("                #")
time.sleep(0.2)
i = os.system('cls')
print("")
print("      #")
print("      # #       #############")
print("      #   #   # #        #")
print("      #    ##   #     ##")
print("      #       # #  #     #")
print("      ##########o##########")
print("       #     #  # #       #")
print("         ##     #   ##    #")
print("       #        # #   #   #")
print("    #############       # #")
print("                          #")
time.sleep(0.2)
i = os.system('cls')
print("                #")
print("              # #")
print("            #   #")
print("          #     #########")
print("          # #   #    #     #")
print("          #   # # #           #")
print("################o###############")
print("  #           # # #   #")
print("     #     #    #   # #")
print("        #########     #")
print("                #   #")
print("                # #")
print("                #")
time.sleep(0.2)
i = os.system('cls')
print("")
print("      #")
print("      # #       #############")
print("      #   #   # #        #")
print("      #    ##   #     ##")
print("      #       # #  #     #")
print("      ##########o##########")
print("       #     #  # #       #")
print("         ##     #   ##    #")
print("       #        # #   #   #")
print("    #############       # #")
print("                          #")
time.sleep(0.2)
i = os.system('cls')
print("                #")
print("              # #")
print("            #   #")
print("          #     #########")
print("          # #   #    #     #")
print("          #   # # #           #")
print("################o###############")
print("  #           # # #   #")
print("     #     #    #   # #")
print("        #########     #")
print("                #   #")
print("                # #")
print("                #")
time.sleep(0.2)
i = os.system('cls')
print("")
print("      #")
print("      # #       #############")
print("      #   #   # #        #")
print("      #    ##   #     ##")
print("      #       # #  #     #")
print("      ##########o##########")
print("       #     #  # #       #")
print("         ##     #   ##    #")
print("       #        # #   #   #")
print("    #############       # #")
print("                          #")
time.sleep(0.2)
i = os.system('cls')
print("                #")
print("              # #")
print("            #   #")
print("          #     #########")
print("          # #   #    #     #")
print("          #   # # #           #")
print("################o###############")
print("  #           # # #   #")
print("     #     #    #   # #")
print("        #########     #")
print("                #   #")
print("                # #")
print("                #")
time.sleep(0.2)
i = os.system('cls')
print("")
print("      #")
print("      # #       #############")
print("      #   #   # #        #")
print("      #    ##   #     ##")
print("      #       # #  #     #")
print("      ##########o##########")
print("       #     #  # #       #")
print("         ##     #   ##    #")
print("       #        # #   #   #")
print("    #############       # #")
print("                          #")
time.sleep(0.2)
i = os.system('cls')
print("                #")
print("              # #")
print("            #   #")
print("          #     #########")
print("          # #   #    #     #")
print("          #   # # #           #")
print("################o###############")
print("  #           # # #   #")
print("     #     #    #   # #")
print("        #########     #")
print("                #   #")
print("                # #")
print("                #")
time.sleep(0.2)
i = os.system('cls')
print("")
print("      #")
print("      # #       #############")
print("      #   #   # #        #")
print("      #    ##   #     ##")
print("      #       # #  #     #")
print("      ##########o##########")
print("       #     #  # #       #")
print("         ##     #   ##    #")
print("       #        # #   #   #")
print("    #############       # #")
print("                          #")
time.sleep(0.2)
i = os.system('cls')
print("                #")
print("              # #")
print("            #   #")
print("          #     #########")
print("          # #   #    #     #")
print("          #   # # #           #")
print("################o###############")
print("  #           # # #   #")
print("     #     #    #   # #")
print("        #########     #")
print("                #   #")
print("                # #")
print("                #")
time.sleep(0.2)
i = os.system('cls')
print("")
print("      #")
print("      # #       #############")
print("      #   #   # #        #")
print("      #    ##   #     ##")
print("      #       # #  #     #")
print("      ##########o##########")
print("       #     #  # #       #")
print("         ##     #   ##    #")
print("       #        # #   #   #")
print("    #############       # #")
print("                          #")
time.sleep(0.2)
i = os.system('cls')
print("                #")
print("              # #")
print("            #   #")
print("          #     #########")
print("          # #   #    #     #")
print("          #   # # #           #")
print("################o###############")
print("  #           # # #   #")
print("     #     #    #   # #")
print("        #########     #")
print("                #   #")
print("                # #")
print("                #")
time.sleep(0.2)
i = os.system('cls')
print("")
print("      #")
print("      # #       #############")
print("      #   #   # #        #")
print("      #    ##   #     ##")
print("      #       # #  #     #")
print("      ##########o##########")
print("       #     #  # #       #")
print("         ##     #   ##    #")
print("       #        # #   #   #")
print("    #############       # #")
print("                          #")
